name: Test Packages
on: [push]
jobs:
    Test-Helper-Base:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Install Node
                uses: actions/setup-node@v4
            -   name:
                run: |
                    cd base
                    npm install
                    npm test