name: Test Packages
on: [push]
jobs:
    Test-Helper-Base:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Install Node
                uses: actions/setup-node@v4
            -   name:
                shell: bash
                run: |
                    chmod a+x _testCommon/jest.sh
                    (cd node; npm install)
                    cd base
                    npm install --include dev
                    npm config set script-shell bash
                    npm ls
                    TOKEN=${{secrets.TEST_STARTGG_API_TOKEN}} npm test -- -s